# ------------------------------------------------------------------
# my_dataset.yaml
# ------------------------------------------------------------------
path: dataset

# Train/val image directories (relative to 'path')
train: train/
val: test/

# --- Class definitions ---
# Number of classes in your dataset
nc: 2 

# Class names in the correct order (0=background, 1=person, etc.)
names: 
  0: mkate 
  1: mcherry

